# markdownlint-cli2 configuration
# https://github.com/DavidAnson/markdownlint-cli2

globs:
  - "**/*.md"

ignores:
  - "node_modules/**"
  - ".claude/skills/**"
  - ".opencode/skills/**"

# markdownlint rules
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md
config:
  default: true

  # MD013 - Line length
  MD013:
    line_length: 120
    heading_line_length: 120
    code_block_line_length: 120

  # MD024 - Multiple headings with the same content
  MD024:
    siblings_only: true

  # MD033 - Inline HTML (allow common elements)
  MD033:
    allowed_elements:
      - br
      - details
      - summary
      - img

  # MD041 - First line in a file should be a top-level heading
  MD041: true

  # MD060 - Table column style
  # CJK全角文字の表示幅を正しく扱えないため無効化
  MD060: false
